apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
data:
  # Los valores deben estar en base64
  # echo -n "admin" | base64 -> YWRtaW4=
  # echo -n "mysecretpassword" | base64 -> bXlzZWNyZXRwYXNzd29yZA==
  database.username: YWRtaW4=
  database.password: bXlzZWNyZXRwYXNzd29yZA==
  api.key: c2VjcmV0LWFwaS1rZXktZm9yLWF1dGg=
