apiVersion: batch/v1
kind: CronJob
metadata:
  name: hola-mundo-cron
  namespace: lab-ingress
spec:
  schedule: "*/1 * * * *"  # Ejecutar cada minuto
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hola-mundo
            image: python:3.9-alpine
            command:
            - /bin/sh
            - -c
            - 'echo "Hola Mundo - $(date)" && sleep 30'
          restartPolicy: OnFailure

